import Foundation
import MLX
import MLXLLM
import MLXLMCommon
import os

/// Cleans transcripts on-device with our own fine-tune: Qwen3.5-0.8B + LoRA trained on
/// dictation cleanup (fillers, self-corrections, punctuation, numbers, spoken formatting
/// commands and lists), quantized for MLX (attention 8-bit, rest 4-bit, ~535 MB).
///
/// It is a normalizer, not a chat model: it was trained only to rewrite the transcript, so
/// questions and commands in it are cleaned, never answered or followed.
///
/// Weights are downloaded from Hugging Face at the revision pinned below (see `PinnedModel`).
/// To ship a new fine-tune, upload it, then run `scripts/pin-cleanup-model.sh` to update the
/// pin; the next app release downloads it and deletes the old one. Debug builds prefer a local
/// model linked by `scripts/install-cleanup-model.sh`, for testing a fine-tune before uploading.
@Observable
final class DictationModelBackend: CleanupBackend {
    nonisolated enum BackendError: LocalizedError {
        case notReady(String)
        case notPublished

        var errorDescription: String? {
            switch self {
            case .notReady(let reason): return reason
            case .notPublished: return "Vedu Scribe isn't available in this build yet"
            }
        }
    }

    private(set) var state: LocalModelState = .idle

    var isNormalizer: Bool { true }
    var modelState: LocalModelState? { state }

    /// Called on every state change so the cleaner can refresh its availability.
    @ObservationIgnored var onStateChange: (() -> Void)?

    @ObservationIgnored private var container: ModelContainer?
    @ObservationIgnored private var loadTask: Task<Void, Never>?
    private let logger = Logger(subsystem: "com.heyvedu.app", category: "DictationModel")

    /// The fixed training prompt; it must match the training repo's `PLAIN_SYSTEM`.
    private nonisolated static let systemPrompt = "Clean up this dictation."

    /// Trained with max_seq_length 1,024 (prompt + output, output ≈ input), so keep each
    /// input chunk well under half of that.
    nonisolated static let chunkTokenBudget = 400

    // MARK: Pinned model

    /// Generated by `scripts/pin-cleanup-model.sh`; an empty revision means not yet published.
    // BEGIN PINNED MODEL
    private nonisolated static let model = PinnedModel(
        displayName: "Vedu Scribe",
        folder: "vedu-scribe",
        repository: "heyvedu/vedu-scribe-0.8b",
        revision: "6a97d98e05c048e13576784576f58133b80ee2cf",
        files: [
            .init(name: "chat_template.jinja", size: 7755,
                  sha256: "273d8e0e683b885071fb17e08d71e5f2a5ddfb5309756181681de4f5a1822d80"),
            .init(name: "config.json", size: 60445,
                  sha256: "a02e0e16a518b5a3baa307941b90f2b19f4730aa775c2babd3993d39de770654"),
            .init(name: "model.safetensors", size: 540713766,
                  sha256: "2dc25debcfd81b93970cf5fa7003df213e3ca451461357b283dba4ea2b4405ea"),
            .init(name: "model.safetensors.index.json", size: 60784,
                  sha256: "437540ae055104cac70097c3b8706d5c46fd821f438b0fa06adddbed3683455f"),
            .init(name: "tokenizer.json", size: 19989339,
                  sha256: "a5cd9732badce41de57e6efce8302930ded1c1188c5f81feb2bd6c24c4a1941f"),
            .init(name: "tokenizer_config.json", size: 1502,
                  sha256: "4d2fc7899270dc76b57a7aa1d5ec3234e6a25934c6e2aea6166f989f1d453892"),
        ]
    )
    // END PINNED MODEL

    #if DEBUG
    /// A local model linked by `scripts/install-cleanup-model.sh`, used instead of the pinned one.
    private nonisolated static var developmentDirectory: URL? {
        let link = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appending(path: "HeyVedu/Models/vedu-scribe-dev", directoryHint: .isDirectory)
            .resolvingSymlinksInPath()
        return FileManager.default.fileExists(atPath: link.appending(path: "config.json").path) ? link : nil
    }
    #endif

    // MARK: Lifecycle

    func availability() -> TextCleaner.Availability {
        switch state {
        case .ready: return .available
        case .idle: return .unavailable("Vedu Scribe isn't loaded yet")
        case .downloading(let fraction):
            let total = Self.model.totalSize / 1_000_000
            let done = Int64(Double(total) * fraction)
            return .unavailable("Downloading Vedu Scribe… \(done) of \(total) MB")
        case .loading: return .unavailable("Loading Vedu Scribe…")
        case .failed(let reason): return .unavailable(reason)
        }
    }

    /// Downloads (first use, or after an update pins a new revision) and loads the model in
    /// the background. Safe to call repeatedly; retries after a failure.
    func warmUp() {
        guard container == nil, loadTask == nil else { return }
        loadTask = Task {
            defer { loadTask = nil }
            do {
                let directory = try await modelDirectory()
                setState(.loading)
                let started = ContinuousClock.now
                // Keep MLX's buffer cache small: the app idles in the menu bar most of the time.
                Memory.cacheLimit = 64 * 1024 * 1024
                // Non-strict: the tokenizer class is `Qwen3_5Tokenizer`, which swift-transformers
                // doesn't list yet; it is the same byte-level BPE as `Qwen2Tokenizer`.
                container = try await LLMModelFactory.shared.loadContainer(
                    from: directory, using: TransformersTokenizerLoader(strict: false))
                DebugTrace.write("vedu-scribe: loaded in \(ContinuousClock.now - started)")
                setState(.ready)
            } catch {
                let reason = (error as? LocalizedError)?.errorDescription ?? error.localizedDescription
                logger.error("Vedu Scribe load failed: \(reason, privacy: .public)")
                setState(.failed(reason))
            }
        }
    }

    /// Frees the model's memory (engine switched away, or app quitting).
    func shutdown() {
        loadTask?.cancel()
        loadTask = nil
        container = nil
        if state != .idle { setState(.idle) }
    }

    private func modelDirectory() async throws -> URL {
        #if DEBUG
        if let local = Self.developmentDirectory {
            DebugTrace.write("vedu-scribe: using local model \(local.path)")
            return local
        }
        #endif
        guard !Self.model.revision.isEmpty else { throw BackendError.notPublished }
        return try await Self.model.ensureDownloaded { [weak self] fraction in
            Task { @MainActor in
                // Progress tasks can land after the download finished; never step back.
                guard let self, self.loadTask != nil, self.state == .idle || self.state.isDownloading else { return }
                self.setState(.downloading(fraction))
            }
        }
    }

    private func setState(_ newState: LocalModelState) {
        state = newState
        onStateChange?()
    }

    // MARK: Cleanup

    func chunks(of transcript: String, instructions: String) async -> [String] {
        await SentenceChunker.chunks(of: transcript, budget: Self.chunkTokenBudget) { [container] text in
            guard let container else { return nil }
            return await container.encode(text).count
        }
    }

    /// Cleans one chunk. An empty result is valid: filler-only input ("um") has no
    /// written form. The model was trained on a fixed prompt, so `instructions` (and with
    /// them the vocabulary) are not used.
    func clean(_ chunk: String, instructions: String) async throws -> String {
        guard let container else {
            throw BackendError.notReady(availability().reason ?? "Vedu Scribe isn't loaded")
        }

        let transcript = Self.sanitize(chunk)
        let input = UserInput(
            chat: [.system(Self.systemPrompt), .user(transcript)],
            // Trained with thinking disabled (empty think block in the prompt).
            additionalContext: ["enable_thinking": false]
        )
        let transcriptTokens = await container.encode(transcript).count
        // Same cap and greedy decoding as the training repo's eval (predict_mlx.py).
        let parameters = GenerateParameters(
            maxTokens: Int(ceil(Double(transcriptTokens) * 1.4)) + 48,
            temperature: 0
        )

        let prepared = try await container.prepare(input: input)
        var output = ""
        for await generation in try await container.generate(input: prepared, parameters: parameters) {
            if case .chunk(let text) = generation { output += text }
        }
        return output
            .replacingOccurrences(of: "<think>", with: "")
            .replacingOccurrences(of: "</think>", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Transcripts are plain speech; strip anything that looks like a chat-template token
    /// so the input can't end the user turn early.
    private nonisolated static func sanitize(_ text: String) -> String {
        text.replacingOccurrences(of: #"<\|[^|>]*\|>"#, with: " ", options: .regularExpression)
    }
}
