import AppKit
import Carbon.HIToolbox

/// Inserts text at the cursor of the frontmost app by briefly taking over the
/// clipboard and posting ⌘V, then restoring the previous clipboard contents.
final class TextInserter {
    private static let restoreDelay: Duration = .milliseconds(500)
    /// nspasteboard.org markers so clipboard managers skip our temporary entry.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    func insert(_ text: String) {
        let pasteboard = NSPasteboard.general
        let saved = Self.snapshot(pasteboard)

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientType)
        item.setData(Data(), forType: Self.autoGeneratedType)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        Self.postPaste()

        Task {
            try? await Task.sleep(for: Self.restoreDelay)
            // If something else wrote to the clipboard meanwhile, leave it alone.
            guard pasteboard.changeCount == ourChangeCount else { return }
            pasteboard.clearContents()
            if !saved.isEmpty { pasteboard.writeObjects(saved) }
        }
    }

    /// Copies concrete data for every type on every item (lazily promised data from
    /// other apps is materialised here or lost).
    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func postPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let key = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
